In [1]:
import numpy as np 

x1 =[[1,1,1,1]]
x2 =[[1,-1,-1,1]]
x3 =[[-1,1,-1,-1]]
x4 =[[1,-1,-1,-1]]

x11 = np.transpose(x1,axes=None)
print(x11)
w1 = x1* x11
print(w1)

x22 = np.transpose(x2,axes=None)
print(x22)
w2 = x2* x22
print(w2)

x33 = np.transpose(x3,axes=None)
print(x33)
w3 = x3* x33
print(w3)

x44 = np.transpose(x4,axes=None)
print(x44)
w4 = x4* x44
print(w4)

w = w1+w2+w3+w4
print (w)

xt1 = np.dot(x1,w)
print (f"xt1={xt1}")

def make_diagonal_zero(matrix):
    for i in range(len(matrix)):
        matrix[i][i]=0
    return matrix

w_rev = make_diagonal_zero(w)
print (w_rev)

xt1 = np.dot(x1,w_rev)
print (xt1)

def activate(x):
    return np.where(x>=0,1,-1)

xt1_act =activate(xt1)
print(xt1_act)

if np.array_equal(x1,xt1_act):
    print ("testing complte")
else:
    print("testing failed")

[[1]
 [1]
 [1]
 [1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 1]
 [-1]
 [-1]
 [ 1]]
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]]
[[-1]
 [ 1]
 [-1]
 [-1]]
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1 -1  1  1]]
[[ 1]
 [-1]
 [-1]
 [-1]]
[[ 1 -1 -1 -1]
 [-1  1  1  1]
 [-1  1  1  1]
 [-1  1  1  1]]
[[ 4 -2  0  2]
 [-2  4  2  0]
 [ 0  2  4  2]
 [ 2  0  2  4]]
xt1=[[4 4 8 8]]
[[ 0 -2  0  2]
 [-2  0  2  0]
 [ 0  2  0  2]
 [ 2  0  2  0]]
[[0 0 4 4]]
[[1 1 1 1]]
testing complte
